# Configuration file for the bot.
# Most of these have built-in sensible defaults and does not need to be set.

[bot]
# Bot token.
token = <your bot token>

# Default prefix if a guild prefix is not set.
# The bot will also respond to mentions.
# default_prefix = c>

# Change to whatever you feel suitable for data storage.
# Only SQLite (with aiosqlite) will be supported by me.
# db_connection_string = sqlite+aiosqlite:///data/database.sqlite3

# Send unhandled exceptions to this webhook URL.
# error_reporting_webhook = <discord webhook url>

# List of users that can add global aliases on this instance.
# alias_managers = <comma-separated list of Discord user IDs>

# Link to your instance's support server.
# support_server_invite = <invite link>

[web]
# Starts a web server for people to link their CHUNITHM-NET/Kamaitachi
# accounts more easily.
#
# enable = false

# The address to listen for requests on
#
# listen_address = 127.0.0.1

# The web server's port.
# The port should be non-privileged (>1024) and the server should stand behind a
# reverse proxy.
#
# port = 5730

# Login server base URL.
#
# Required if you use the default login script (https://gist.github.com/beer-psi/0eb8d3e50ae753388a6d4a4af5678a2e).
# If you provide a custom implementation, this is not needed.
# Do not have a trailing slash.
# base_url = https://example.com

# [GoatCounter](https://goatcounter.com) tracking URL, used for basic analytics.
# This is optional, and you can set it to blank to disable.
# goatcounter = https://something.goatcounter.com/count

# If the assets/jackets directory exists, let the web server serve them.
# serve_assets = false

# If nothing matches the given URI, the user is redirected to this URL with the same path.
# Do not have a trailing slash.
# fallback_url = https://example.com

# Trust X-Forwarded-* headers sent to the web server. Enable if running the server
# behind a proxy (e.g. NGINX or Cloudflare).
# trust_proxy = false

[credentials]
# Used for retrieving data from https://db.chunỉrec.net
# Get one from https://developer.chunirec.net/
# chunirec_token = <token>

# Enable users to sync scores with https://kamaitachi.xyz
# kamaitachi_client_id = CI<something>

# Only required if you enable the login server, as this is used to facilitate OAuth2 only.
# kamaitachi_client_secret =

# Kamaitachi API key for bot access to public stuff e.g. leaderboards
# kamaitachi_api_key =

# The GoatCounter [API key](https://www.goatcounter.com/help/api), used to send
# pageviews on web server requests that don't serve HTML like /songs and /invite.
# goatcounter_api_key =

# A SEGA ID account with a CHUNITHM International profile can be used for commands
# that just needs CHUNITHM-NET access, but doesn't need any particular profiles.
# sega_id_username =
# sega_id_password =

[icons]
# Display rank icons as emojis instead of text.
# sssp = <:rank_sssp:1234>
# sss =
# ssp =
# ss =
# sp =
# s =
# aaa =
# aa =
# a =
# bbb =
# bb =
# b =
# c =
# d =
# bonus_icon_map =
# bonus_icon_exp =
# bonus_icon_point =
# bonus_icon_chance =
# bonus_icon_critical =
# bonus_icon_gamepoint =
# bonus_icon_selection =

[legal]
# Link to the bot's privacy policy.
# privacy_policy =

# Link to the bot's terms of service.
# terms_of_service =

[dangerous]
# Development mode:
# - enables debug logging
# - shows SQL parameters in database exceptions
# - always allow running debugging commands
# dev = false

# TOTP key for debugging commands, required to run debugging commands in production mode.
# debug_totp =

[seeds]
# Database seeds configuration.
#
# Local seeds. Load seeds from a filesystem path.
# type = local
# path = chuni_penguin/database/seeds
#
# Seeds from a Git repository. Username and email are used as user.name and user.email
# in Git when syncing back changes to the Git repository.
# type = git
# url = https://github.com/beer-psi/chuni-penguin.git
# branch = develop
# username =
# email =
