version: "3.9"

services:
  bot:
    build:
      dockerfile: Dockerfile
      args:
        - UID=1000
        - GID=1000
        - GIT_SHA
    volumes:
      - ./data:/code/data:rw
      - ./assets:/code/assets:rw
      - ./bot.ini:/code/bot.ini
    expose:
      - 5730
    restart: unless-stopped
    # this is to allow a grace period for guessing games to finish
    stop_grace_period: "6m"
