services:
  bot:
    image: "ghcr.io/beer-psi/chuni-penguin:trunk"
    volumes:
      - "./data:/code/data:rw" # database
      - "./assets:/code/assets:rw" # assets
      - "./bot.ini:/code/bot.ini" # config
      - "/home/user/.cache/chuni-penguin:/code/.cache/chuni-penguin:rw" # cache for sdvxin chart views
    expose:
      - 5730
    restart: unless-stopped
    # this is to allow a grace period for guessing games to finish
    stop_grace_period: "6m30s"
