[tool.poetry]
name = "chuninewbot"
version = "0.1.0"
description = ""
authors = ["beerpiss <lacvtg.a1.2023@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
"discord.py" = "^2.1.0"
aiohttp = "^3.8.5"
yarl = "^1.8.2"
beautifulsoup4 = "^4.11.2"
python-dotenv = "^1.0.0"
dataclasses-json = "^0.5.7"
aiolimiter = "^1.0.0"
lxml = "^4.9.2"
pillow = "^9.5.0"
jarowinkler = "^1.2.3"
alembic = "^1.11.2"
sqlalchemy = {version = "^2.0.19", extras = ["asyncio"]}

[tool.isort]
profile = "black"

[tool.poetry.dev-dependencies]
black = "^23.1.0"
isort = "^5.12.0"

[tool.poetry.group.dev.dependencies]
black = "^23.3.0"
isort = "^5.12.0"
types-beautifulsoup4 = "^4.12.0.1"
jishaku = "^2.5.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
