from chuni_penguin.views.b30 import B30View
from chuni_penguin.views.b30n20 import B30N20View
from chuni_penguin.views.courses import CourseListView
from chuni_penguin.views.embeds import EmbedPaginationView
from chuni_penguin.views.login import LoginFlowView
from chuni_penguin.views.profile import ProfileView
from chuni_penguin.views.recent import RecentRecordsView
from chuni_penguin.views.select_to_compare import SelectToCompareView
from chuni_penguin.views.songlist import SonglistView
