import binascii
from contextlib import closing
from datetime import UTC, datetime
from decimal import Decimal
from math import ceil
from pathlib import Path
from typing import IO, TYPE_CHECKING, Any, Literal

from PIL import Image, ImageDraw, ImageFilter, ImageFont

from chuni_penguin.constants import ASSETS_DIR, CACHE_DIR
from chuni_penguin.types import ComboLamp, Score
from chuni_penguin.utils import floor_to_ndp

if TYPE_CHECKING:
    from collections.abc import Sequence

    from chuni_penguin.database import UserConfig

NOTO_SANS_JP_24 = ImageFont.truetype(
    ASSETS_DIR / "fonts" / "NotoSansJP-Regular.ttf", 24
)
NOTO_SANS_JP_24_BOLD = ImageFont.truetype(
    ASSETS_DIR / "fonts" / "NotoSansJP-Bold.ttf", 24
)
NOTO_SANS_JP_28_MEDIUM = ImageFont.truetype(
    ASSETS_DIR / "fonts" / "NotoSansJP-Medium.ttf", 28
)
NOTO_SANS_32_BOLD = ImageFont.truetype(ASSETS_DIR / "fonts" / "NotoSans-Bold.ttf", 32)
NOTO_SANS_JP_32_BOLD = ImageFont.truetype(
    ASSETS_DIR / "fonts" / "NotoSansJP-Bold.ttf", 32
)
NOTO_SANS_JP_40_BOLD = ImageFont.truetype(
    ASSETS_DIR / "fonts" / "NotoSansJP-Bold.ttf", 40
)
NOTO_SANS_JP_64_BOLD = ImageFont.truetype(
    ASSETS_DIR / "fonts" / "NotoSansJP-Bold.ttf", 64
)
INTER_32 = ImageFont.truetype(ASSETS_DIR / "fonts" / "Inter_28pt-Regular.ttf", 32)
INTER_40_BOLD = ImageFont.truetype(ASSETS_DIR / "fonts" / "Inter_28pt-Bold.ttf", 40)
INTER_44_BOLD = ImageFont.truetype(ASSETS_DIR / "fonts" / "Inter_28pt-Bold.ttf", 44)

B30_IMAGE_WIDTH = 1872
B30_HEADER_HEIGHT = 220
B30_HEADER_SPACING = 185
B30_OLD_NEW_SPACING = 130
B30_FOOTER_SPACING = 95
B30_FOOTER_HEIGHT = 70
B30_ENTRY_WIDTH = 350
B30_ENTRY_HEIGHT = 215
B30_ENTRY_WIDTH_SPACING = 15
B30_ENTRY_HEIGHT_SPACING = 25
B30_JACKET_WIDTH = 110
B30_JACKET_HEIGHT = 110
INVITE_LINK = "https://chunithm.beerpsi.cc/invite"


def _make_background_image(file: Path, width: int, height: int):
    with Image.open(file) as im:
        with closing(im):
            im = im.resize((im.width * height // im.height, height))

        with closing(im):
            im = im.crop(
                (
                    (im.width - width) / 2,
                    (im.height - height) / 2,
                    (im.width + width) / 2,
                    (im.height + height) / 2,
                )
            )

        with closing(im):
            im = im.filter(ImageFilter.GaussianBlur(5))

        if im.mode != "RGBA":
            with closing(im):
                im = im.convert("RGBA")

    return im


def _paste_alpha_composite(
    im1: Image.Image,
    im2: Image.Image,
    box: Image.Image | tuple[int, int] | tuple[int, int, int, int] | None = None,
):
    im1_rgba = im1 if im1.mode == "RGBA" else im1.convert("RGBA")

    with closing(Image.new("RGBA", im1.size)) as im2_padded:
        im2_padded.paste(im2, box)

        result = Image.alpha_composite(im1, im2_padded)

        if im1.mode != "RGBA":
            im1_rgba.close()

        return result


def _render_b30_template(
    record_slots: int,
    new_record_slots: int | None = None,
    rating_title: str = "RATING",
    footer_text: str = "Design by Tukkun | Generated by chuni penguin#3127",
    invite_link: str = INVITE_LINK,
    *,
    uncross_verse: bool = False,
    bg_path: Path | None = None,
    overlay_path: Path | None = None,
    logo_path: Path | None = None,
    part_header_path: Path | None = None,
    part_date_path: Path | None = None,
    part_old_path: Path | None = None,
    part_new_path: Path | None = None,
):
    if bg_path is None:
        bg_path = ASSETS_DIR / "b50" / "default" / "bg.webp"

    if overlay_path is None:
        overlay_path = ASSETS_DIR / "b50" / "b50_overlay.webp"

    if logo_path is None:
        if uncross_verse:
            logo_path = ASSETS_DIR / "b50" / "default" / "logo_uncrossverse.webp"
        else:
            logo_path = ASSETS_DIR / "b50" / "default" / "logo.webp"

    if part_header_path is None:
        part_header_path = ASSETS_DIR / "b50" / "b50_part_header.webp"

    if part_date_path is None:
        part_date_path = ASSETS_DIR / "b50" / "b50_part_date.webp"

    if part_old_path is None:
        part_old_path = ASSETS_DIR / "b50" / "b50_part_old.webp"

    if part_new_path is None:
        part_new_path = ASSETS_DIR / "b50" / "b50_part_new.webp"

    cache_parts = [
        1,  # version number for when constants like fonts, etc. need to be updated
        record_slots,
        new_record_slots,
        rating_title,
        footer_text,
        invite_link,
        uncross_verse,
        bg_path.stat().st_mtime,
        overlay_path.stat().st_mtime,
        part_header_path.stat().st_mtime,
        logo_path.stat().st_mtime,
        part_date_path.stat().st_mtime,
    ]

    if new_record_slots is not None:
        cache_parts.append(part_old_path.stat().st_mtime)
        cache_parts.append(part_new_path.stat().st_mtime)

    cache_key = binascii.crc32(":".join([str(p) for p in cache_parts]).encode("utf-8"))
    cached_file = CACHE_DIR / "b50" / f"template_{cache_key}.webp"

    if cached_file.exists():
        with Image.open(cached_file) as im:
            if im.mode != "RGBA":
                im = im.convert("RGBA")

            return im

    row_num = ceil(record_slots / 5)

    # calculate image height
    b30_image_height = (
        B30_HEADER_HEIGHT
        + B30_HEADER_SPACING
        + (B30_ENTRY_HEIGHT + B30_ENTRY_HEIGHT_SPACING) * row_num
        + B30_FOOTER_SPACING
        + B30_FOOTER_HEIGHT
    )

    # Add a gap between old rating and new rating, if it is provided
    if new_record_slots is not None:
        new_row_num = ceil(new_record_slots / 5)
        b30_image_height += B30_OLD_NEW_SPACING + (B30_ENTRY_HEIGHT + 15) * new_row_num

    # draw background, copy so we can paste things on top of it
    with closing(
        _make_background_image(bg_path, B30_IMAGE_WIDTH, b30_image_height)
    ) as im:
        b30_image = im.copy()

    # draw background overlay
    with (
        closing(b30_image),
        closing(
            _make_background_image(overlay_path, b30_image.width, b30_image.height)
        ) as b30_overlay,
    ):
        b30_image = Image.alpha_composite(b30_image, b30_overlay)

    # draw header overlay
    with Image.open(part_header_path) as im, closing(im), closing(b30_image):
        b30_image = _paste_alpha_composite(b30_image, im, (0, 0))

    with Image.open(logo_path) as im, closing(im), closing(b30_image):
        b30_image = _paste_alpha_composite(
            b30_image, im, (1442 + (400 - im.width) // 2, 10 + (289 - im.height) // 2)
        )

    # draw generated date overlay
    with Image.open(part_date_path) as im, closing(im), closing(b30_image):
        b30_image = _paste_alpha_composite(b30_image, im, (1492, 310))

    # draw semitransparent rectangles to darken footer
    with (
        closing(b30_image),
        closing(Image.new("RGBA", b30_image.size)) as b30_semitransparent_base,
    ):
        b30_semitransparent_draw = ImageDraw.Draw(b30_semitransparent_base)
        # draw footer separation line
        b30_semitransparent_draw.rectangle(
            (
                0,
                b30_image.height - B30_FOOTER_HEIGHT - 2,
                b30_image.width,
                b30_image.height - B30_FOOTER_HEIGHT,
            ),
            fill=(0, 0, 0, 200),
        )
        # darken footer
        b30_semitransparent_draw.rectangle(
            (
                0,
                b30_image.height - B30_FOOTER_HEIGHT,
                b30_image.width,
                b30_image.height,
            ),
            fill=(0, 0, 0, 120),
        )

        # paste the darkened parts onto the image
        b30_image = Image.alpha_composite(b30_image, b30_semitransparent_base)

    if new_record_slots is not None:
        # draw the "OLD CHARTS" and "NEW CHARTS" separators
        with Image.open(part_old_path) as im, closing(im), closing(b30_image):
            b30_image = _paste_alpha_composite(b30_image, im, (0, 300))

        with Image.open(part_new_path) as im, closing(im), closing(b30_image):
            b30_image = _paste_alpha_composite(b30_image, im, (0, 1870))

    b30_draw = ImageDraw.Draw(b30_image)

    # draw the text "RATING"
    b30_draw.text(
        (790, 22),
        rating_title,
        fill="#DDDDDD",
        font=INTER_32,
    )

    # draw the credits
    b30_draw.text(
        (30, b30_image.height - 57), footer_text, fill="#DDDDDD", font=INTER_32
    )

    # determine the size of invite link to properly right-align it
    invite_link_text_length = b30_draw.textlength(invite_link, INTER_32)

    # draw the invite link
    b30_draw.text(
        (b30_image.width - 30 - invite_link_text_length, b30_image.height - 57),
        invite_link,
        fill="#DDDDDD",
        font=INTER_32,
    )

    if new_record_slots is not None:
        b30_draw.text(
            (40, 316),
            "OLD CHARTS",
            fill="#FFFFFF",
            font=INTER_40_BOLD,
        )
        b30_draw.text(
            (40, 1886),
            "NEW CHARTS",
            fill="#FFFFFF",
            font=INTER_40_BOLD,
        )

    b30_image.save(cached_file, lossless=True)

    return b30_image


def _render_b30_entry(
    b30_image: Image.Image,
    record: Score,
    i: int,
    x: int,
    y: int,
    user_config: "UserConfig | None" = None,
):
    # get the jacket
    song_id = record.song.id
    jacket_basename = f"{song_id}"

    if song_id == 2698 and user_config is not None:
        if user_config.synthesis_alt_jacket == "none":
            jacket_basename = "__nonexistent"
        elif user_config.synthesis_alt_jacket != "default":
            jacket_basename = f"{song_id}_{user_config.synthesis_alt_jacket}"

    jacket_path = ASSETS_DIR / "jackets" / f"{jacket_basename}.webp"
    prerendered_path = (
        ASSETS_DIR
        / "jackets"
        / f"{jacket_basename}_{record.chart.difficulty.value}.webp"
    )

    if prerendered_path.exists():
        with Image.open(prerendered_path) as prerendered, closing(prerendered):
            b30_image.paste(prerendered, (x, y), prerendered)
    else:
        # draw the base image based on the difficulty
        b30_base_image_path = (
            ASSETS_DIR / "b50" / f"b50_base_{record.chart.difficulty.value}.webp"
        )

        with Image.open(b30_base_image_path) as b30_base_image, closing(b30_base_image):
            b30_image.paste(b30_base_image, (x, y), b30_base_image)

        # we use try/catch on jacket processing to gracefully fail to a black image
        # if the jacket is missing or corrupted
        try:
            with Image.open(jacket_path) as jacket, closing(jacket):
                jacket = jacket.resize(
                    (B30_JACKET_WIDTH, B30_JACKET_HEIGHT), Image.Resampling.LANCZOS
                )

        except (FileNotFoundError, ValueError):
            # fallback to a black background if anything fails
            jacket = Image.new("RGB", (B30_JACKET_WIDTH, B30_JACKET_HEIGHT), 0)

        # draw the jacket art onto the card
        with closing(jacket):
            b30_image.paste(jacket, (x + 10, y + 60))

    b30_draw = ImageDraw.Draw(b30_image)

    # if the title doesn't fit the b30 entry rectangle, shorten it until it fits.
    title = record.song.title
    title_length = b30_draw.textlength(title, NOTO_SANS_JP_32_BOLD)

    while title_length > B30_ENTRY_WIDTH - 25:
        title = title[:-1]
        title_length = b30_draw.textlength(title + "...", NOTO_SANS_JP_32_BOLD)

    # draw the title
    b30_draw.text(
        (x + 10, y),
        title + ("..." if title != record.song.title else ""),
        fill="#FFFFFF",
        font=(
            NOTO_SANS_JP_32_BOLD
            if record.song.id != 2831  # Street - χρόνος
            else NOTO_SANS_32_BOLD
        ),
    )

    # draw the score
    b30_draw.text(
        (x + 132, y + 50),
        f"{record.score:,}",
        fill="#FFFFFF",
        font=NOTO_SANS_JP_32_BOLD,
    )

    # draw the lamps
    rank_lamp = f"[{record.rank}]"
    b30_draw.text(
        (x + 132, y + 90),
        rank_lamp,
        fill="#DDDDDD",
        font=NOTO_SANS_JP_24,
    )

    if record.combo_lamp != ComboLamp.none:
        rank_lamp_width = b30_draw.textlength(rank_lamp + " ", NOTO_SANS_JP_24)

        if record.combo_lamp == ComboLamp.all_justice_critical:
            combo_lamp = "[AJC]"
            combo_lamp_color = "#FFDF75"
        elif record.combo_lamp == ComboLamp.all_justice:
            combo_lamp = "[AJ]"
            combo_lamp_color = "#FFDF75"
        elif record.combo_lamp == ComboLamp.full_combo:
            combo_lamp = "[FC]"
            combo_lamp_color = "#28F31A"
        else:
            msg = f"unhandled combo lamp {record.combo_lamp}"
            raise ValueError(msg)

        b30_draw.text(
            (x + 132 + rank_lamp_width, y + 90),
            combo_lamp,
            fill=combo_lamp_color,
            font=NOTO_SANS_JP_24_BOLD,
        )

    # draw the timestamp and judgements if available
    extra_info = ""

    if record.achieved_at is not None:
        difference = datetime.now(UTC) - record.achieved_at

        if difference.days >= 365:
            delta = f"{difference.days // 365}y"
        elif difference.days >= 30:
            delta = f"{difference.days // 30}mo"
        elif difference.days >= 1:
            delta = f"{difference.days}d"
        elif difference.seconds >= 3600:
            delta = f"{difference.seconds // 3600}h"
        elif difference.seconds >= 60:
            delta = f"{difference.seconds // 60}m"
        elif difference.seconds >= 1:
            delta = f"{difference.seconds}s"
        else:
            delta = "0s"

        extra_info = delta

    if (judgements := record.judgements) is not None:
        if extra_info:
            extra_info += f" | {judgements.justice_critical} – {judgements.justice} – {judgements.attack} – {judgements.miss}"  # noqa: RUF001
        else:
            extra_info += f"{judgements.justice_critical} – {judgements.justice} – {judgements.attack} – {judgements.miss}"  # noqa: RUF001

    b30_draw.text(
        (x + 10, y + 176),
        extra_info,
        fill="#BBBBBB",
        font=NOTO_SANS_JP_24,
    )

    # draw the rank of the b30 entry
    rank_text_length = b30_draw.textlength(f"#{i + 1}", NOTO_SANS_JP_28_MEDIUM)
    b30_draw.text(
        (x + B30_ENTRY_WIDTH - 10 - rank_text_length, y + 174),
        f"#{i + 1}",
        fill="#FFFFFF",
        font=NOTO_SANS_JP_28_MEDIUM,
    )

    # draw the internal level
    b30_draw.text(
        (x + 132, y + 128),
        f"{record.chart.internal_level:.1f}",
        fill="#FFFFFF",
        font=NOTO_SANS_JP_28_MEDIUM,
    )

    # draw the rating value
    rating_text_length = b30_draw.textlength(
        f"{record.rating:.2f}", NOTO_SANS_JP_40_BOLD
    )
    rating_value_color = "#FFFFFF"

    if record.score >= 1_009_000:
        rating_value_color = "#FAFFA5"

    b30_draw.text(
        (x + B30_ENTRY_WIDTH - 10 - rating_text_length, y + 118),
        f"{record.rating:.2f}",
        fill=rating_value_color,
        font=NOTO_SANS_JP_40_BOLD,
    )


def render_b30(
    *,
    player_name: str,
    output: IO[bytes],
    records: "Sequence[Score]",
    record_slots: int = 30,
    new_records: "Sequence[Score] | None" = None,
    new_record_slots: int = 20,
    current_rating: float | None = None,
    user_config: "UserConfig | None" = None,
    uncross_verse: bool = False,
    theme: Literal["xverse", "default"] = "default",
    output_format: str = "PNG",
    output_params: dict[str, Any] | None = None,
):
    if len(records) > record_slots:
        msg = "More records provided than number of record slots"
        raise ValueError(msg)

    if new_records is not None and len(new_records) > new_record_slots:
        msg = "More new records provided than number of new record slots"
        raise ValueError(msg)

    if theme != "default":
        bg_path = ASSETS_DIR / "b50" / theme / "bg.webp"
        logo_path = (
            ASSETS_DIR / "b50" / theme / "logo_uncrossverse.webp"
            if uncross_verse
            else ASSETS_DIR / "b50" / theme / "logo.webp"
        )
    else:
        bg_path = None
        logo_path = None

    b30_image = _render_b30_template(
        record_slots,
        new_record_slots if new_records is not None else None,
        rating_title="RATING" if new_records is not None else "NAIVE RATING",
        uncross_verse=uncross_verse,
        bg_path=bg_path,
        logo_path=logo_path,
    )
    b30_draw = ImageDraw.Draw(b30_image)

    # draw player name
    player_name_length = b30_draw.textlength(player_name, NOTO_SANS_JP_64_BOLD)
    b30_draw.text(
        (390 - player_name_length / 2, 64),
        player_name,
        fill="#FFFFFF",
        font=NOTO_SANS_JP_64_BOLD,
    )

    # get rating values
    total_rating = sum(
        (item.rating or Decimal(0) for item in records), start=Decimal(0)
    )
    average = floor_to_ndp(total_rating / record_slots, 4)
    new_average = 0

    # draw the rating information
    if new_records is None:
        raw_rating_text = f"({average:.4f})"
        final_rating = floor_to_ndp(average, 2)
    else:
        new_total_rating = sum(
            (item.rating or Decimal(0) for item in new_records), start=Decimal(0)
        )
        new_average = floor_to_ndp(
            new_total_rating / new_record_slots,
            4,
        )
        overall_average = floor_to_ndp(
            (total_rating + new_total_rating) / (record_slots + new_record_slots), 4
        )
        raw_rating_text = f"({overall_average:.4f})"
        final_rating = floor_to_ndp(overall_average, 2)

    if current_rating is not None:
        final_rating = current_rating

    rating_text = f"{final_rating:.2f}"

    # set rating color
    rating_thresholds = [
        (17.00, 10),
        (16.00, 9),
        (15.25, 8),
        (14.50, 7),
        (13.25, 6),
        (12.00, 5),
        (10.00, 4),
        (7.00, 3),
        (4.00, 2),
    ]

    rating_tier = 1
    for threshold, tier in rating_thresholds:
        if final_rating >= threshold:
            rating_tier = tier
            break

    # draw the rating number
    digit_x = 810
    digit_count = 0
    if final_rating < 10:
        digit_x = 835
        digit_count = 1

    for char in rating_text:
        # draw each digit of the rating number
        digit_count += 1
        image_name = (
            f"rating_{rating_tier}_{char}.webp"
            if char != "."
            else f"rating_{rating_tier}_dot.webp"
        )
        digit_path = ASSETS_DIR / "b50" / image_name

        with Image.open(digit_path) as digit_im, closing(digit_im), closing(b30_image):
            b30_image = _paste_alpha_composite(b30_image, digit_im, (digit_x, 58))

        digit_x += 40

        if digit_count == 1 or digit_count == 4:
            digit_x += 10

    b30_draw = ImageDraw.Draw(b30_image)

    # determine the size of raw rating text to properly right-align it
    raw_rating_text_length = b30_draw.textlength(raw_rating_text, INTER_32)

    # draw the raw rating
    b30_draw.text(
        (1090 - raw_rating_text_length, 162),
        raw_rating_text,
        fill="#DDDDDD",
        font=INTER_32,
    )

    # determine the size of the timestamp to properly right-align it
    updated_text = f"{datetime.now(UTC).strftime('%Y-%m-%d')}"
    updated_length = b30_draw.textlength(updated_text, INTER_40_BOLD)

    # draw the timestamp
    b30_draw.text(
        (
            b30_image.width - updated_length - 40,
            318,
        ),
        updated_text,
        fill="#DDDDDD",
        font=INTER_40_BOLD,
    )

    # best30
    for i, record in enumerate(records):
        # top left corner of each b30 entry
        # - the initial 30 is left margin
        # - the (i % 5) and (i // 5) are the b30's position on the grid, so this goes
        # left to right, top to bottom
        x = 30 + (i % 5) * (B30_ENTRY_WIDTH + B30_ENTRY_WIDTH_SPACING)
        y = (
            B30_HEADER_HEIGHT
            + B30_HEADER_SPACING
            + (i // 5) * (B30_ENTRY_HEIGHT + B30_ENTRY_HEIGHT_SPACING)
        )

        _render_b30_entry(b30_image, record, i, x, y, user_config)

    if new_records is not None:
        b30_draw = ImageDraw.Draw(b30_image)

        # draw b30 average
        b30_draw.text(
            (420, 314),
            f"{average:.4f}",
            fill="#000000",
            font=INTER_44_BOLD,
        )

        # draw n20 average
        b30_draw.text(
            (420, 1884),
            f"{new_average:.4f}",
            fill="#000000",
            font=INTER_44_BOLD,
        )

        for i, record in enumerate(new_records):
            x = 30 + (i % 5) * (B30_ENTRY_WIDTH + B30_ENTRY_WIDTH_SPACING)

            y = (
                B30_HEADER_HEIGHT
                + B30_HEADER_SPACING
                + 6 * (B30_ENTRY_HEIGHT + B30_ENTRY_HEIGHT_SPACING)
                + B30_OLD_NEW_SPACING
                + (i // 5) * (B30_ENTRY_HEIGHT + B30_ENTRY_HEIGHT_SPACING)
            )

            _render_b30_entry(b30_image, record, i, x, y, user_config)

    if output_params is None:
        output_params = {}

    if (
        output_format == "PNG"
        and "optimize" not in output_params
        and "compress_level" not in output_params
    ):
        output_params["compress_level"] = 3

    b30_image.save(output, output_format, **output_params)
    b30_image.close()
    output.seek(0)
