"""create indexes

Revision ID: f0a878ad32b2
Revises: 47839ec2cbd5
Create Date: 2025-03-22 11:38:03.063261

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f0a878ad32b2"
down_revision: Union[str, None] = "47839ec2cbd5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

conventions = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_`%(constraint_name)s`",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("aliases", schema=None) as batch_op:
        batch_op.create_index("ix_aliases_alias", ["alias"], unique=False)
        batch_op.create_index("ix_aliases_guild_id", ["guild_id"], unique=False)
        batch_op.create_index("ix_aliases_song_id", ["song_id"], unique=False)

    op.execute("CREATE INDEX ix_aliases_lower_alias ON aliases (LOWER(alias))")

    with op.batch_alter_table("chunirec_charts", schema=None) as batch_op:
        batch_op.create_index("ix_chunirec_charts_const", ["const"], unique=False)
        batch_op.create_index(
            "ix_chunirec_charts_difficulty", ["difficulty"], unique=False
        )
        batch_op.create_index("ix_chunirec_charts_level", ["level"], unique=False)
        batch_op.create_index("ix_chunirec_charts_song_id", ["song_id"], unique=False)
        batch_op.create_index(
            "ix_chunirec_charts_song_id_difficulty",
            ["song_id", "difficulty"],
            unique=True,
        )

    with op.batch_alter_table("chunirec_songs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_chunirec_songs_available", ["available"], unique=False
        )
        batch_op.create_index("ix_chunirec_songs_genre", ["genre"], unique=False)
        batch_op.create_index("ix_chunirec_songs_jacket", ["jacket"], unique=False)
        batch_op.create_index("ix_chunirec_songs_removed", ["removed"], unique=False)
        batch_op.create_index("ix_chunirec_songs_title", ["title"], unique=False)

    op.execute(
        "CREATE INDEX ix_chunirec_songs_lower_title ON chunirec_songs (LOWER(title))"
    )

    with op.batch_alter_table("guess_leaderboard", schema=None) as batch_op:
        batch_op.create_index(
            "ix_guess_leaderboard_guild_id", ["guild_id"], unique=False
        )
        batch_op.create_index(
            "ix_guess_leaderboard_guild_id_difficulty",
            ["guild_id", "difficulty"],
            unique=False,
        )

    with op.batch_alter_table(
        "sdvxin", schema=None, naming_convention=conventions
    ) as batch_op:
        batch_op.drop_constraint("uq_sdvxin_id", type_="unique")
        batch_op.create_index(
            "ix_sdvxin_id_difficulty", ["id", "difficulty", "end_index"], unique=True
        )
        batch_op.create_index(
            "ix_sdvxin_song_id_difficulty", ["song_id", "difficulty"], unique=True
        )
        batch_op.drop_constraint("fk_sdvxin_song_id_chunirec_songs", type_="foreignkey")
        batch_op.create_foreign_key(
            "fk_sdvxin_song_id_chunirec_charts",
            "chunirec_charts",
            ["song_id", "difficulty"],
            ["song_id", "difficulty"],
        )

    with op.batch_alter_table("song_jackets", schema=None) as batch_op:
        batch_op.drop_constraint("uq_song_jackets_jacket_url", type_="unique")
        batch_op.create_index("ix_song_jackets_jacket_url", ["jacket_url"], unique=True)
        batch_op.create_index("ix_song_jackets_song_id", ["song_id"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("song_jackets", schema=None) as batch_op:
        batch_op.drop_index("ix_song_jackets_song_id")
        batch_op.drop_index("ix_song_jackets_jacket_url")
        batch_op.create_unique_constraint("uq_song_jackets_jacket_url", ["jacket_url"])

    with op.batch_alter_table(
        "sdvxin", schema=None, naming_convention=conventions
    ) as batch_op:
        batch_op.drop_index("ix_sdvxin_song_id_difficulty")
        batch_op.drop_index("ix_sdvxin_id_difficulty")
        batch_op.drop_constraint(
            "fk_sdvxin_song_id_chunirec_charts", type_="foreignkey"
        )
        batch_op.create_foreign_key(
            "fk_sdvxin_song_id_chunirec_songs",
            "chunirec_songs",
            ["song_id"],
            ["id"],
        )
        batch_op.create_unique_constraint("uq_sdvxin_id", ["id", "difficulty"])

    with op.batch_alter_table("guess_leaderboard", schema=None) as batch_op:
        batch_op.drop_index("ix_guess_leaderboard_guild_id_difficulty")
        batch_op.drop_index("ix_guess_leaderboard_guild_id")

    with op.batch_alter_table("chunirec_songs", schema=None) as batch_op:
        batch_op.drop_index("ix_chunirec_songs_lower_title")
        batch_op.drop_index("ix_chunirec_songs_title")
        batch_op.drop_index("ix_chunirec_songs_removed")
        batch_op.drop_index("ix_chunirec_songs_jacket")
        batch_op.drop_index("ix_chunirec_songs_genre")
        batch_op.drop_index("ix_chunirec_songs_available")

    with op.batch_alter_table("chunirec_charts", schema=None) as batch_op:
        batch_op.drop_index("ix_chunirec_charts_song_id_difficulty")
        batch_op.drop_index("ix_chunirec_charts_song_id")
        batch_op.drop_index("ix_chunirec_charts_level")
        batch_op.drop_index("ix_chunirec_charts_difficulty")
        batch_op.drop_index("ix_chunirec_charts_const")

    with op.batch_alter_table("aliases", schema=None) as batch_op:
        batch_op.drop_index("ix_aliases_lower_alias")
        batch_op.drop_index("ix_aliases_song_id")
        batch_op.drop_index("ix_aliases_guild_id")
        batch_op.drop_index("ix_aliases_alias")

    # ### end Alembic commands ###
