"""supporter/contributor roles

Revision ID: f27a9e31efab
Revises: 4d8020ae6521
Create Date: 2025-12-01 14:48:24.331751

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f27a9e31efab"
down_revision: Union[str, None] = "4d8020ae6521"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cookies", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_contributor",
                sa.Boolean(),
                server_default=sa.text("(FALSE)"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "is_supporter",
                sa.Boolean(),
                server_default=sa.text("(FALSE)"),
                nullable=False,
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cookies", schema=None) as batch_op:
        batch_op.drop_column("is_supporter")
        batch_op.drop_column("is_contributor")
    # ### end Alembic commands ###
