"""make guess leaderboard unique by discord + guild ID

Revision ID: e8f3627eef6d
Revises: 3ca7cf4f0623
Create Date: 2025-03-14 12:05:52.190018

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e8f3627eef6d"
down_revision: Union[str, None] = "3ca7cf4f0623"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

naming_convention = {"pk": "pk_%(table_name)s"}


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "guess_leaderboard",
        schema=None,
        naming_convention=naming_convention,
        recreate="always",
    ) as batch_op:
        batch_op.drop_constraint("pk_guess_leaderboard", type_="primary")
        batch_op.add_column(
            sa.Column("id", sa.Integer(), nullable=False),
            insert_before="discord_id",
        )
        batch_op.create_primary_key("pk_guess_leaderboard", ["id"])
        batch_op.alter_column(
            "discord_id",
            existing_type=sa.INTEGER(),
            type_=sa.BigInteger(),
            nullable=False,
        )
        batch_op.create_unique_constraint(
            "_discord_id_guild_id_uc", ["discord_id", "guild_id"]
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guess_leaderboard", schema=None) as batch_op:
        batch_op.drop_constraint("_discord_id_guild_id_uc", type_="unique")
        batch_op.alter_column(
            "discord_id",
            existing_type=sa.BigInteger(),
            type_=sa.INTEGER(),
            nullable=True,
        )
        batch_op.drop_column("id")
    # ### end Alembic commands ###
