"""denylist

Revision ID: be44dbe4b4bf
Revises: 2ce91159c498
Create Date: 2025-08-10 15:49:04.339640

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "be44dbe4b4bf"
down_revision: Union[str, None] = "2ce91159c498"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "denylist",
        sa.Column("object_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("object_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("denylist")
    # ### end Alembic commands ###
