"""allow one sdvxin chart view to be assigned to multiple charts

Revision ID: 4d8020ae6521
Revises: 9f59797184ae
Create Date: 2025-10-31 21:00:02.283339

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4d8020ae6521"
down_revision: Union[str, None] = "9f59797184ae"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sdvxin", schema=None) as batch_op:
        batch_op.drop_index("ix_sdvxin_id_difficulty")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sdvxin", schema=None) as batch_op:
        batch_op.create_index(
            "ix_sdvxin_id_difficulty", ["id", "difficulty", "end_index"], unique=True
        )
    # ### end Alembic commands ###
