"""add Tachi chart ID to charts

Revision ID: f7a38a1c89a3
Revises: 6d9947d87ec3
Create Date: 2025-09-26 23:20:37.939859

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f7a38a1c89a3"
down_revision: Union[str, None] = "6d9947d87ec3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chunirec_charts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("tachi_chart_id", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chunirec_charts", schema=None) as batch_op:
        batch_op.drop_column("tachi_chart_id")
    # ### end Alembic commands ###
