"""track alias uses

Revision ID: 2ce91159c498
Revises: 6cba06215123
Create Date: 2025-08-01 19:32:49.907325

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2ce91159c498"
down_revision: Union[str, None] = "6cba06215123"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("aliases", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("uses", sa.Integer(), server_default=sa.text("0"), nullable=False)
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("aliases", schema=None) as batch_op:
        batch_op.drop_column("uses")
    # ### end Alembic commands ###
