"""add denylist reason

Revision ID: 9f59797184ae
Revises: 9e4907a4b966
Create Date: 2025-10-17 16:16:21.601174

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9f59797184ae"
down_revision: Union[str, None] = "9e4907a4b966"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("denylist", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "reason", sa.String(), server_default=sa.text("(NULL)"), nullable=True
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("denylist", schema=None) as batch_op:
        batch_op.drop_column("reason")
    # ### end Alembic commands ###
