"""add wikiwiki title override

Revision ID: 48e74e7cff0b
Revises: 0405631b21f3
Create Date: 2025-05-22 14:36:59.859092

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "48e74e7cff0b"
down_revision: Union[str, None] = "0405631b21f3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chunirec_songs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "wikiwiki_title",
                sa.String(),
                server_default=sa.text("(NULL)"),
                nullable=True,
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chunirec_songs", schema=None) as batch_op:
        batch_op.drop_column("wikiwiki_title")
    # ### end Alembic commands ###
