"""fix song_id datatype

Revision ID: c9ba77d3080b
Revises: e7f25090f7cf
Create Date: 2025-10-01 15:23:01.001832

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c9ba77d3080b"
down_revision: Union[str, None] = "e7f25090f7cf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("aliases", schema=None) as batch_op:
        batch_op.alter_column(
            "song_id", existing_type=sa.TEXT(), type_=sa.Integer(), nullable=False
        )

    with op.batch_alter_table("chunirec_charts", schema=None) as batch_op:
        batch_op.alter_column(
            "song_id", existing_type=sa.TEXT(), type_=sa.Integer(), nullable=False
        )

    with op.batch_alter_table("sdvxin", schema=None) as batch_op:
        batch_op.alter_column(
            "song_id", existing_type=sa.TEXT(), type_=sa.Integer(), nullable=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("sdvxin", schema=None) as batch_op:
        batch_op.alter_column(
            "song_id", existing_type=sa.Integer(), type_=sa.TEXT(), nullable=True
        )

    with op.batch_alter_table("chunirec_charts", schema=None) as batch_op:
        batch_op.alter_column(
            "song_id", existing_type=sa.Integer(), type_=sa.TEXT(), nullable=True
        )

    with op.batch_alter_table("aliases", schema=None) as batch_op:
        batch_op.alter_column(
            "song_id", existing_type=sa.Integer(), type_=sa.TEXT(), nullable=True
        )
    # ### end Alembic commands ###
