"""linked gate conditions

Revision ID: e2da443dc3e2
Revises: 166e390c5661
Create Date: 2026-02-04 15:14:52.261925

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from chuni_penguin.database.base import DateTimeUTC

# revision identifiers, used by Alembic.
revision: str = "e2da443dc3e2"
down_revision: Union[str, None] = "166e390c5661"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "linked_gate_conditions",
        sa.Column("linked_gate_id", sa.Integer(), nullable=False),
        sa.Column("level", sa.Integer(), nullable=False),
        sa.Column("region", sa.String(), nullable=False),
        sa.Column("difficulty", sa.String(), nullable=False),
        sa.Column("life", sa.Integer(), nullable=False),
        sa.Column("recovery_life", sa.Integer(), nullable=False),
        sa.Column("damage_miss", sa.Integer(), nullable=False),
        sa.Column("damage_attack", sa.Integer(), nullable=False),
        sa.Column("damage_justice", sa.Integer(), nullable=False),
        sa.Column("start_date", DateTimeUTC(), nullable=False),
        sa.Column("end_date", DateTimeUTC(), nullable=True),
        sa.ForeignKeyConstraint(
            ["linked_gate_id"],
            ["linked_gates.id"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("linked_gate_id", "level", "region"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("linked_gate_conditions")
    # ### end Alembic commands ###
