"""personal bests

Revision ID: 62eb03aabe2b
Revises: a44dd650f884
Create Date: 2026-01-10 14:46:52.208755

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "62eb03aabe2b"
down_revision: Union[str, None] = "a44dd650f884"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "personal_bests",
        sa.Column("discord_id", sa.BigInteger(), nullable=False),
        sa.Column("network", sa.String(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("difficulty", sa.String(), nullable=False),
        sa.Column("score", sa.Integer(), nullable=False),
        sa.Column("justice_heaven", sa.Integer(), nullable=True),
        sa.Column("justice_critical", sa.Integer(), nullable=True),
        sa.Column("justice", sa.Integer(), nullable=True),
        sa.Column("attack", sa.Integer(), nullable=True),
        sa.Column("miss", sa.Integer(), nullable=True),
        sa.Column("max_combo", sa.Integer(), nullable=True),
        sa.Column(
            "clear_lamp", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "combo_lamp", sa.Integer(), server_default=sa.text("0"), nullable=False
        ),
        sa.Column(
            "chain_lamp", sa.Integer(), server_default=sa.text("NULL"), nullable=True
        ),
        sa.Column("achieved_at", sa.DateTime(), nullable=True),
        sa.Column("last_played_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["song_id", "difficulty"],
            ["chunirec_charts.song_id", "chunirec_charts.difficulty"],
            name="fk_personal_bests_song_id_difficulty_chunirec_charts",
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["song_id"], ["chunirec_songs.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("discord_id", "network", "song_id", "difficulty"),
    )
    with op.batch_alter_table("personal_bests", schema=None) as batch_op:
        batch_op.create_index(
            "ix_personal_bests_discord_id", ["discord_id"], unique=False
        )
        batch_op.create_index(
            "ix_personal_bests_discord_id_song_id",
            ["discord_id", "song_id"],
            unique=False,
        )
        batch_op.create_index(
            "ix_personal_bests_discord_id_song_id_difficulty",
            ["discord_id", "song_id", "difficulty"],
            unique=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("personal_bests", schema=None) as batch_op:
        batch_op.drop_index("ix_personal_bests_discord_id_song_id_difficulty")
        batch_op.drop_index("ix_personal_bests_discord_id_song_id")
        batch_op.drop_index("ix_personal_bests_discord_id")

    op.drop_table("personal_bests")
    # ### end Alembic commands ###
