"""change backing type of DateTimeUTC

Revision ID: 1f99105ae5b4
Revises: d1122c2cacab
Create Date: 2026-01-14 09:38:14.918364

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f99105ae5b4"
down_revision: Union[str, None] = "d1122c2cacab"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("UPDATE command_uses SET created_at = UNIXEPOCH(created_at, 'subsec')")
    op.execute(
        "UPDATE pending_kamaitachi_imports SET created_at = UNIXEPOCH(created_at, 'subsec')"
    )
    op.execute(
        "UPDATE personal_bests SET achieved_at = UNIXEPOCH(achieved_at, 'subsec') WHERE achieved_at IS NOT NULL"
    )
    op.execute(
        "UPDATE personal_bests SET last_played_at = UNIXEPOCH(last_played_at, 'subsec') WHERE last_played_at IS NOT NULL"
    )

    with op.batch_alter_table("command_uses", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            type_=sa.REAL(),
            nullable=False,
            server_default=sa.text("UNIXEPOCH('subsec')"),
        )

    with op.batch_alter_table("pending_kamaitachi_imports", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            type_=sa.REAL(),
            nullable=False,
            server_default=sa.text("UNIXEPOCH('subsec')"),
        )

    with op.batch_alter_table("personal_bests", schema=None) as batch_op:
        batch_op.alter_column("achieved_at", type_=sa.REAL(), nullable=True)
        batch_op.alter_column("last_played_at", type_=sa.REAL(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("personal_bests", schema=None) as batch_op:
        batch_op.alter_column("last_played_at", type_=sa.DATETIME(), nullable=True)
        batch_op.alter_column("achieved_at", type_=sa.DATETIME(), nullable=True)

    with op.batch_alter_table("pending_kamaitachi_imports", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            type_=sa.DATETIME(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        )

    with op.batch_alter_table("command_uses", schema=None) as batch_op:
        batch_op.alter_column(
            "created_at",
            type_=sa.DATETIME(),
            nullable=False,
            server_default=sa.text("CURRENT_TIMESTAMP"),
        )
    # ### end Alembic commands ###

    op.execute(
        "UPDATE command_uses SET created_at = DATETIME(created_at, 'unixepoch', 'subsec')"
    )
    op.execute(
        "UPDATE pending_kamaitachi_imports SET created_at = DATETIME(created_at, 'unixepoch', 'subsec')"
    )
    op.execute(
        "UPDATE personal_bests SET achieved_at = DATETIME(achieved_at, 'unixepoch', 'subsec') WHERE achieved_at IS NOT NULL"
    )
    op.execute(
        "UPDATE personal_bests SET last_played_at = DATETIME(last_played_at, 'unixepoch', 'subsec') WHERE last_played_at IS NOT NULL"
    )
