"""add duration to songs

Revision ID: 12d14e1c5575
Revises: e44228715c2a
Create Date: 2026-04-24 22:13:16.957484

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "12d14e1c5575"
down_revision: Union[str, None] = "e44228715c2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chunirec_songs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "duration",
                sa.Integer(),
                server_default=sa.text("(NULL)"),
                nullable=True,
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chunirec_songs", schema=None) as batch_op:
        batch_op.drop_column("duration")
    # ### end Alembic commands ###
