"""command permissions

Revision ID: d8f8c9819006
Revises: 304e2e43729c
Create Date: 2026-01-13 10:58:04.174121

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from chuni_penguin.database.base import UInt64Integer

# revision identifiers, used by Alembic.
revision: str = "d8f8c9819006"
down_revision: Union[str, None] = "304e2e43729c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "command_permissions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guild_id", UInt64Integer(), nullable=False),
        sa.Column("index", sa.Integer(), nullable=False),
        sa.Column(
            "primary_target_type",
            sa.Enum("guild", "role", "channel", "user", name="primarypermissiontarget"),
            nullable=False,
        ),
        sa.Column("primary_target_id", UInt64Integer(), nullable=False),
        sa.Column(
            "secondary_target_type",
            sa.Enum("all", "group", "command", name="secondarypermissiontarget"),
            nullable=False,
        ),
        sa.Column("secondary_target_name", sa.String(), nullable=False),
        sa.Column("is_allowed", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("command_permissions")
    # ### end Alembic commands ###
