"""Cookie friend_code

Revision ID: ba5be27156ff
Revises: e2da443dc3e2
Create Date: 2026-02-25 20:39:45.227115

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ba5be27156ff"
down_revision: Union[str, None] = "e2da443dc3e2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cookies", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "friend_code",
                sa.String(length=32),
                nullable=True,
                server_default=sa.text("NULL"),
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cookies", schema=None) as batch_op:
        batch_op.drop_column("friend_code")
    # ### end Alembic commands ###
