"""new exciting bullshit linked verse mechanics

Revision ID: 0632579fe10c
Revises: 12d14e1c5575
Create Date: 2026-04-26 00:08:35.078038

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0632579fe10c"
down_revision: Union[str, None] = "12d14e1c5575"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("linked_gate_conditions", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "recovery_life_combo_type",
                sa.String(),
                server_default=sa.text("'combo'"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "is_local_matching_required",
                sa.Boolean(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "survivors_required",
                sa.Integer(),
                server_default=sa.text("(NULL)"),
                nullable=True,
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("linked_gate_conditions", schema=None) as batch_op:
        batch_op.drop_column("survivors_required")
        batch_op.drop_column("is_local_matching_required")
        batch_op.drop_column("recovery_life_combo_type")
    # ### end Alembic commands ###
