"""command uses

Revision ID: 6d34ec73965f
Revises: 62eb03aabe2b
Create Date: 2026-01-11 12:59:26.256445

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

from chuni_penguin.database.base import DateTimeUTC

# revision identifiers, used by Alembic.
revision: str = "6d34ec73965f"
down_revision: Union[str, None] = "62eb03aabe2b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "command_uses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("guild_id", sa.BigInteger(), nullable=True),
        sa.Column("channel_id", sa.BigInteger(), nullable=False),
        sa.Column("author_id", sa.BigInteger(), nullable=False),
        sa.Column("prefix", sa.String(), nullable=False),
        sa.Column("command", sa.String(), nullable=False),
        sa.Column("is_failure", sa.Boolean(), nullable=False),
        sa.Column("is_app_command", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            DateTimeUTC(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("command_uses")
    # ### end Alembic commands ###
