"""specific chart availability

Revision ID: d1122c2cacab
Revises: 89641906c5d2
Create Date: 2026-01-14 07:49:10.671637

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d1122c2cacab"
down_revision: Union[str, None] = "89641906c5d2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table(
        "chunirec_charts",
        schema=None,
        partial_reordering=("charter", "version", "available", "tachi_chart_id"),
    ) as batch_op:
        batch_op.add_column(
            sa.Column(
                "available",
                sa.Boolean(),
                nullable=False,
                server_default=sa.text("FALSE"),
            )
        )
    # ### end Alembic commands ###

    op.execute("""
        UPDATE chunirec_charts
        SET available = (SELECT available FROM chunirec_songs WHERE chunirec_charts.song_id = chunirec_songs.id)
    """)

    # 10th anniversary ults were not available at the time of writing
    op.execute(
        "UPDATE chunirec_charts SET available = 0 WHERE difficulty = 'ULT' AND song_id IN (53, 59, 73, 76, 145, 230, 288, 399, 438, 1101)"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chunirec_charts", schema=None) as batch_op:
        batch_op.drop_column("available")
    # ### end Alembic commands ###
