"""linked verse

Revision ID: 166e390c5661
Revises: 1f99105ae5b4
Create Date: 2026-02-04 14:27:03.241998

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "166e390c5661"
down_revision: Union[str, None] = "1f99105ae5b4"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "linked_gates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("color", sa.String(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column(
            "available", sa.Boolean(), server_default=sa.text("(FALSE)"), nullable=False
        ),
        sa.Column("open_condition", sa.String(), nullable=False),
        sa.Column("unlock_condition", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["song_id"], ["chunirec_songs.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )


# ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("linked_gates")
    # ### end Alembic commands ###
