"""index for pending_kamaitachi_imports

Revision ID: a44dd650f884
Revises: c1c21cbbd46f
Create Date: 2026-01-01 22:01:37.688105

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a44dd650f884"
down_revision: Union[str, None] = "c1c21cbbd46f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pending_kamaitachi_imports", schema=None) as batch_op:
        batch_op.create_index(
            "ix_pending_kamaitachi_imports_discord_id", ["discord_id"], unique=False
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("pending_kamaitachi_imports", schema=None) as batch_op:
        batch_op.drop_index("ix_pending_kamaitachi_imports_discord_id")
    # ### end Alembic commands ###
