"""nullable jacket filename

Revision ID: c361540d731b
Revises: ba5be27156ff
Create Date: 2026-03-15 19:25:30.780430

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "c361540d731b"
down_revision: Union[str, None] = "ba5be27156ff"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chunirec_songs", schema=None) as batch_op:
        batch_op.alter_column("jacket", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chunirec_songs", schema=None) as batch_op:
        batch_op.alter_column("jacket", existing_type=sa.VARCHAR(), nullable=False)
    # ### end Alembic commands ###
