"""Store calculated rating in PBs

Revision ID: e44228715c2a
Revises: f184cc61d80f
Create Date: 2026-04-09 22:45:21.761961

"""

import decimal
from decimal import Decimal
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e44228715c2a"
down_revision: Union[str, None] = "f184cc61d80f"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

FC_OVERPOWER_BONUS = Decimal("0.5")
AJ_OVERPOWER_BONUS = Decimal("0.5")
AJC_OVERPOWER_BONUS = Decimal("0.25")


def floor_to_ndp(number: decimal.Decimal, dp: int) -> decimal.Decimal:
    with decimal.localcontext() as ctx:
        ctx.rounding = decimal.ROUND_FLOOR
        return round(number, dp)


def calculate_whole_rating(score: int, internal_level: float | None) -> int:
    il10000 = int((internal_level or 0) * 10000)

    if score >= 1_009_000:
        return il10000 + 21_500
    if score >= 1_007_500:
        return il10000 + 20_000 + (score - 1_007_500)
    if score >= 1_005_000:
        return il10000 + 15_000 + (score - 1_005_000) * 2
    if score >= 1_000_000:
        return il10000 + 10_000 + (score - 1_000_000)
    if score >= 975_000:
        return int(il10000 + (score - 975_000) * 2 / 5)
    if score >= 900_000:
        effective_il10000 = max(il10000 - 50_000, 0)
        return int(
            effective_il10000
            + (score - 900_000) / 75_000 * (il10000 - effective_il10000)
        )
    if score >= 800_000:
        effective_il10000 = max(il10000 - 50_000, 0)
        return int(
            effective_il10000 / 2
            + ((score - 800_000) / 100_000 * (effective_il10000 / 2))
        )
    if score >= 500_000:
        effective_il10000 = max(il10000 - 50_000, 0)
        return int((score - 500_000) / 300_000 * (effective_il10000 / 2))

    return 0


def calculate_overpower_base(score: int, internal_level: float) -> Decimal:
    if score >= 1_007_500:
        sss_bonus = Decimal(score - 1_007_500) / 10000 * 15
        rawop = Decimal(str(internal_level)) * 5 + 10 + sss_bonus
    else:
        rawop = Decimal(calculate_whole_rating(score, internal_level)) / 10000 * 5

    # For rank S and above, OP is floored to the nearest 0.005
    # Otherwise, OP is floored to the nearest 0.05
    rounding = 2 if score >= 975_000 else 1
    op_floor = floor_to_ndp(rawop, rounding)

    with decimal.localcontext() as ctx:
        ctx.rounding = decimal.ROUND_HALF_UP
        op_ceil = round(rawop, rounding)

    return (op_floor + op_ceil) / 2


def calculate_play_overpower(overpower_base: Decimal, combo_lamp: int) -> Decimal:
    play_overpower = overpower_base

    if combo_lamp >= 1:
        play_overpower += FC_OVERPOWER_BONUS

    if combo_lamp >= 2:
        play_overpower += AJ_OVERPOWER_BONUS

    if combo_lamp == 3:
        play_overpower += AJC_OVERPOWER_BONUS

    return play_overpower


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("personal_bests", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "rating", sa.Integer(), server_default=sa.text("(NULL)"), nullable=True
            )
        )
        batch_op.add_column(
            sa.Column(
                "overpower",
                sa.Integer(),
                server_default=sa.text("(NULL)"),
                nullable=True,
            )
        )

    op.execute("""
        UPDATE personal_bests
        SET
            rating = (CASE
                WHEN c.const IS NULL THEN NULL
                WHEN personal_bests.score >= 1009000 THEN CAST(ROUND(c.const * 100) AS INT) + 215
                WHEN personal_bests.score >= 1007500 THEN CAST(ROUND(c.const * 100) AS INT) + 200 + (personal_bests.score - 1007500) / 100
                WHEN personal_bests.score >= 1005000 THEN CAST(ROUND(c.const * 100) AS INT) + 150 + (personal_bests.score - 1005000) * 2 / 100
                WHEN personal_bests.score >= 1000000 THEN CAST(ROUND(c.const * 100) AS INT) + 100 + (personal_bests.score - 1000000) / 100
                WHEN personal_bests.score >= 975000 THEN CAST(ROUND(c.const * 100) AS INT) + (personal_bests.score - 975000) * 2 / 500
                WHEN personal_bests.score >= 900000 THEN MAX(CAST(ROUND(c.const * 100) AS INT) - 500, 0) + (personal_bests.score - 900000) * (CAST(ROUND(c.const * 100) AS INT) - MAX(CAST(ROUND(c.const * 100) AS INT) - 500, 0)) / 75000
                WHEN personal_bests.score >= 800000 THEN MAX(CAST(ROUND(c.const * 100) AS INT) - 500, 0) / 2 + ((personal_bests.score - 800000) * (MAX(CAST(ROUND(c.const * 100) AS INT) - 500, 0) / 2) / 100000)
                WHEN personal_bests.score >= 500000 THEN (score - 500000) * (MAX(CAST(ROUND(c.const * 100) AS INT) - 500, 0) / 2) / 300000
                ELSE 0
            END)
        FROM chunirec_charts c
        WHERE personal_bests.song_id = c.song_id AND personal_bests.difficulty = c.difficulty
    """)

    # I am NOT redoing OP math in SQL man the rounding sucks
    conn = op.get_bind()

    if conn is not None:
        for row in conn.execute(
            sa.text("""
                SELECT pb.rowid, c.const, pb.score, pb.combo_lamp
                FROM personal_bests pb
                JOIN chunirec_charts c ON pb.song_id = c.song_id AND pb.difficulty = c.difficulty
                WHERE pb.rating IS NOT NULL AND c.const IS NOT NULL
            """)
        ):
            overpower = calculate_play_overpower(
                calculate_overpower_base(row.score, row.const),
                row.combo_lamp,
            )
            conn.execute(
                sa.text(
                    "UPDATE personal_bests SET overpower = :overpower WHERE ROWID = :rowid"
                ),
                {"overpower": int(overpower * 1000), "rowid": row.rowid},
            )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("personal_bests", schema=None) as batch_op:
        batch_op.drop_column("rating")
        batch_op.drop_column("overpower")
    # ### end Alembic commands ###
