"""unique command permissions

Revision ID: 89641906c5d2
Revises: d8f8c9819006
Create Date: 2026-01-13 11:30:16.268304

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "89641906c5d2"
down_revision: Union[str, None] = "d8f8c9819006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("command_permissions", schema=None) as batch_op:
        batch_op.create_index(
            "ix_command_permissions_primary_target_secondary_target",
            [
                "primary_target_type",
                "primary_target_id",
                "secondary_target_type",
                "secondary_target_name",
            ],
            unique=True,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("command_permissions", schema=None) as batch_op:
        batch_op.drop_index("ix_command_permissions_primary_target_secondary_target")
    # ### end Alembic commands ###
