"""user config

Revision ID: 9b0c79087522
Revises: f0a878ad32b2
Create Date: 2025-04-07 16:42:39.056603

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9b0c79087522"
down_revision: Union[str, None] = "f0a878ad32b2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_configs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("discord_id", sa.BigInteger(), nullable=False),
        sa.Column("synthesis_alt_jacket", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("discord_id"),
    )
    with op.batch_alter_table("user_configs", schema=None) as batch_op:
        batch_op.create_index("ix_user_configs_discord_id", ["discord_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_configs", schema=None) as batch_op:
        batch_op.drop_index("ix_user_configs_discord_id")

    op.drop_table("user_configs")
    # ### end Alembic commands ###
