"""easter egg tracking

Revision ID: 753e71fc26da
Revises: f7a38a1c89a3
Create Date: 2025-09-30 18:29:28.330632

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "753e71fc26da"
down_revision: Union[str, None] = "f7a38a1c89a3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "easter_eggs_found",
        sa.Column("discord_id", sa.BigInteger(), nullable=False),
        sa.Column("easter_egg", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("discord_id", "easter_egg"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("easter_eggs_found")
    # ### end Alembic commands ###
