"""is hidden on chuninet song flag

Revision ID: e7f25090f7cf
Revises: 753e71fc26da
Create Date: 2025-10-01 13:30:02.674244

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e7f25090f7cf"
down_revision: Union[str, None] = "753e71fc26da"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chunirec_songs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "is_hidden_on_chuninet",
                sa.Boolean(),
                server_default=sa.text("(FALSE)"),
                nullable=False,
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chunirec_songs", schema=None) as batch_op:
        batch_op.drop_column("is_hidden_on_chuninet")
    # ### end Alembic commands ###
