"""courses

Revision ID: 75ed42605cb2
Revises: c9ba77d3080b
Create Date: 2025-10-05 11:10:50.956073

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "75ed42605cb2"
down_revision: Union[str, None] = "c9ba77d3080b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "courses",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "cls",
            sa.Enum(
                "I", "II", "III", "IV", "V", "INFINITE", "EXTRA", name="courseclass"
            ),
            nullable=False,
        ),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("version", sa.String(), nullable=False),
        sa.Column("is_duplicate_track_allowed", sa.Boolean(), nullable=False),
        sa.Column("life", sa.Integer(), nullable=False),
        sa.Column("recovery_life", sa.Integer(), nullable=False),
        sa.Column("clear_life", sa.Integer(), nullable=False),
        sa.Column("damage_miss", sa.Integer(), nullable=False),
        sa.Column("damage_attack", sa.Integer(), nullable=False),
        sa.Column("damage_justice", sa.Integer(), nullable=False),
        sa.Column("damage_jcrit", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "course_tracks",
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("track", sa.Integer(), nullable=False),
        sa.Column("level", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["course_id"], ["courses.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("course_id", "track"),
    )
    op.create_table(
        "course_track_charts",
        sa.Column("course_id", sa.Integer(), nullable=False),
        sa.Column("track", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("difficulty", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["course_id", "track"],
            ["course_tracks.course_id", "course_tracks.track"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["course_id"], ["courses.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["song_id", "difficulty"],
            ["chunirec_charts.song_id", "chunirec_charts.difficulty"],
            onupdate="CASCADE",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["song_id"], ["chunirec_songs.id"], onupdate="CASCADE", ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("course_id", "track", "song_id", "difficulty"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("course_track_charts")
    op.drop_table("course_tracks")
    op.drop_table("courses")
    # ### end Alembic commands ###
