"""add chunirec ID

Revision ID: 0405631b21f3
Revises: ab685e768548
Create Date: 2025-05-22 13:26:24.820650

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0405631b21f3"
down_revision: Union[str, None] = "ab685e768548"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chunirec_songs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "chunirec_id",
                sa.String(),
                nullable=True,
                default=None,
                server_default=sa.text("NULL"),
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("chunirec_songs", schema=None) as batch_op:
        batch_op.drop_column("chunirec_id")
    # ### end Alembic commands ###
