"""split guess leaderboard by game type

Revision ID: 6cba06215123
Revises: 48e74e7cff0b
Create Date: 2025-06-24 06:21:49.152759

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6cba06215123"
down_revision: Union[str, None] = "48e74e7cff0b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guess_leaderboard", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "game_type",
                sa.String(),
                server_default=sa.text("(NULL)"),
                nullable=True,
            )
        )
        batch_op.alter_column("score", existing_type=sa.INTEGER(), nullable=False)
        batch_op.drop_constraint("_discord_id_guild_id_difficulty_uc", type_="unique")
        batch_op.create_unique_constraint(
            "_discord_id_guild_id_difficulty_game_type_uc",
            ["discord_id", "guild_id", "difficulty", "game_type"],
        )
        batch_op.create_index(
            "ix_guess_leaderboard_guild_id_difficulty_game_type",
            ["guild_id", "difficulty", "game_type"],
            unique=False,
        )
        batch_op.create_index(
            "ix_guess_leaderboard_guild_id_game_type",
            ["guild_id", "game_type"],
            unique=False,
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("guess_leaderboard", schema=None) as batch_op:
        batch_op.drop_index("ix_guess_leaderboard_guild_id_game_type")
        batch_op.drop_index("ix_guess_leaderboard_guild_id_difficulty_game_type")
        batch_op.drop_constraint(
            "_discord_id_guild_id_difficulty_game_type_uc", type_="unique"
        )
        batch_op.create_unique_constraint(
            "_discord_id_guild_id_difficulty_uc",
            ["discord_id", "guild_id", "difficulty"],
        )
        batch_op.alter_column("score", existing_type=sa.INTEGER(), nullable=True)
        batch_op.drop_column("game_type")
    # ### end Alembic commands ###
