"""add privacy mode

Revision ID: ab685e768548
Revises: 9b0c79087522
Create Date: 2025-04-15 11:00:59.638497

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ab685e768548"
down_revision: Union[str, None] = "9b0c79087522"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    with op.batch_alter_table("user_configs", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "privacy_mode",
                sa.Boolean(),
                nullable=False,
                default=False,
                server_default=sa.text("FALSE"),
            )
        )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user_configs", schema=None) as batch_op:
        batch_op.drop_column("privacy_mode")
    # ### end Alembic commands ###
