COG_LIST: list[str] = [
    "cogs.help",
    "cogs.database",
    "cogs.web",
    "cogs.botutils",
    "cogs.autocompleters",
    "cogs.events",
    "cogs.fluff",
    "cogs.gaming",
    "cogs.misc",
    "cogs.chunithm.auth",
    "cogs.chunithm.kamaitachi",
    "cogs.chunithm.profile",
    "cogs.chunithm.records",
    "cogs.chunithm.search",
    "cogs.chunithm.tools",
]
