name: "Bot CI"

on:
  push:
    branches:
      - "develop"
      - "trunk"
    paths: &filelist
      - ".github/workflows/ci.yaml"
      - "chuni_penguin/**"
      - "dbutils/**"
      - "packages/**"
      - "patches/**"
      - "tests/**"
      - "launcher.py"
      - "pyproject.toml"
      - "uv.lock"
      - "Dockerfile"
      - ".dockerignore"
  pull_request:
    branches:
      - "develop"
    paths: *filelist
  workflow_dispatch:

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  test:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd" # v5

      - name: "Install uv"
        uses: "astral-sh/setup-uv@5a7eac68fb9809dea845d802897dc5c723910fa3" # v7
        with:
          enable-cache: true
          cache-dependency-glob: "**/uv.lock"

      - name: "Install dependencies"
        run: "uv sync --frozen"

      - name: "Linting"
        run: "uv run ruff check"
        env:
          RUFF_OUTPUT_FORMAT: "github"

      - name: "Type checking"
        run: "uv run basedpyright"

      - name: "Run tests"
        run: "uv run pytest -Werror -v --html=report.html --self-contained-html tests"

      - name: "Upload test report"
        if: "always()"
        uses: "actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4" # v5
        with:
          name: "test-report"
          path: "report.html"
          if-no-files-found: "error"

  build:
    runs-on: "ubuntu-latest"
    needs: ["test"]
    permissions:
      packages: "write"
      contents: "read"
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd" # v5

      - name: "Commit hash"
        run: 'echo "SHORT_SHA=$(git rev-parse --short HEAD)" >> $GITHUB_ENV'

      - name: "(unfortunately) closed source components"
        run: |
          curl -L "$CR_COG_LINK" -o "chuni_penguin/$CR_COG_PATH"
          echo "COG_LIST += ['chuni_penguin.$CR_COG_NAME']" >> chuni_penguin/cogs/__init__.py
        env:
          CR_COG_LINK: "${{ secrets.CR_COG_LINK }}"
          CR_COG_PATH: "${{ secrets.CR_COG_PATH }}"
          CR_COG_NAME: "${{ secrets.CR_COG_NAME }}"

      - name: "Set up QEMU"
        uses: "docker/setup-qemu-action@c7c53464625b32c7a7e944ae62b3e17d2b600130" # v3

      - name: "Set up Docker Buildx"
        uses: "docker/setup-buildx-action@e468171a9de216ec08956ac3ada2f0791b6bd435" # v3

      - name: "Log in to Docker Hub"
        uses: "docker/login-action@5e57cd118135c172c3672efd75eb46360885c0ef" # v3
        with:
          registry: "ghcr.io"
          username: "${{ github.actor }}"
          password: "${{ secrets.GITHUB_TOKEN }}"

      - name: "Extract metadata (tags, labels) for Docker"
        id: "meta"
        uses: "docker/metadata-action@318604b99e75e41977312d83839a89be02ca4893" # v5
        with:
          images: "ghcr.io/beer-psi/chuni-penguin"

      - name: "Build and push"
        uses: "docker/build-push-action@263435318d21b8e681c14492fe198d362a7d2c83" # v6
        with:
          build-args: |
            GIT_SHA=${{ env.SHORT_SHA }}
            UID=${{ vars.UID }}
            GID=${{ vars.GID }}
          context: "."
          push: "${{ github.event_name == 'push' || github.event_name == 'workflow_dispatch' }}"
          tags: "${{ steps.meta.outputs.tags }}"
          labels: "${{ steps.meta.outputs.labels }}"
          cache-from: "type=gha"
          cache-to: "type=gha,mode=max"

  deploy:
    runs-on: "ubuntu-latest"
    needs: ["test", "build"]
    if: "github.event_name == 'push' || github.event_name == 'workflow_dispatch'"
    steps:
      - name: "Tailscale"
        uses: "tailscale/github-action@a392da0a182bba0e9613b6243ebd69529b1878aa" # v4
        with:
          oauth-client-id: "${{ secrets.TS_OAUTH_CLIENT_ID }}"
          oauth-secret: "${{ secrets.TS_OAUTH_SECRET }}"
          tags: "tag:ci"
          use-cache: "true"
          ping: "${{ secrets.SSH_HOST }}"

      - name: "Setup SSH"
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_ed25519
          echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts

          chmod 600 ~/.ssh/id_ed25519 ~/.ssh/known_hosts
        env:
          SSH_PRIVATE_KEY: "${{ secrets.SSH_PRIVATE_KEY }}"
          SSH_KNOWN_HOSTS: "${{ secrets.SSH_KNOWN_HOSTS }}"

      - name: "Deploy staging"
        if: "github.ref == 'refs/heads/develop'"
        run: 'ssh beerpsi@"$SSH_HOST" /mnt/sdb1/chuni-penguin-develop/deploy.sh'
        env:
          SSH_HOST: "${{ secrets.SSH_HOST }}"

      - name: "Deploy production"
        if: "github.ref == 'refs/heads/trunk'"
        run: 'ssh beerpsi@"$SSH_HOST" /mnt/sdb1/chuninewbot/deploy.sh'
        env:
          SSH_HOST: "${{ secrets.SSH_HOST }}"
