name: Deploy

on:
  push:
    branches:
      - trunk
    paths:
      - "api/**"
      - "cogs/**"
      - "utils/**"
      - "views/**"
      - "bot.py"
      - "poetry.lock"
      - "pyproject.toml"
      - "web.py"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy bot
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SSH_HOST }}
          username: beerpsi
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd /home/beerpsi/chuninewbot

            git pull

            /home/beerpsi/.local/bin/poetry install

            /home/beerpsi/.local/bin/poetry run alembic upgrade head
            systemctl --user restart chunibot
