name: "Unit tests"

on:
  push:
    branches:
      - "develop"
      - "trunk"
    paths:
      - ".github/workflows/deploy.yaml"
      - "chunithm_net/**"
      - "cogs/**"
      - "database/**"
      - "dbutils/**"
      - "tests/**"
      - "utils/**"
      - "bot.py"
      - "pyproject.toml"
      - "uv.lock"
      - "web.py"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: "Check out repository"
        uses: "actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8" # v5

      - name: "Install uv"
        uses: "astral-sh/setup-uv@b75a909f75acd358c2196fb9a5f1299a9a8868a4" # v6

      - name: "Install dependencies"
        run: "uv sync --group test --frozen"

      - name: "Run tests"
        run: "uv run pytest -v --html=report.html --self-contained-html tests"

      - name: "Upload test report"
        if: "always()"
        uses: "actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02" # v4
        with:
          name: "test-report"
          path: "report.html"
          if-no-files-found: "error"
